---
name: "Install Tools with deps"
description: "Automatically install development tools using the deps tool"
author: "Flanksource"

branding:
  icon: "download"
  color: "blue"

inputs:
  tools:
    description: "List of tools to install (comma-separated or multiline)"
    required: true
  version:
    description: "Version of deps to use (e.g., v1.0.0 or latest)"
    required: false
    default: "latest"
  GITHUB_TOKEN:
    description: "GitHub token for accessing the API and avoiding rate limit"
    required: false

outputs:
  tools-installed:
    description: "JSON array of installed tools with versions"
    value: ${{ steps.report.outputs.tools-installed }}

runs:
  using: "composite"
  steps:
    - name: Setup cache paths
      id: cache-paths
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "deps-bin=$HOME/.local/bin" >> $GITHUB_OUTPUT
          echo "deps-cache=$HOME/.deps" >> $GITHUB_OUTPUT
          echo "tools-dir=$HOME/.local/opt" >> $GITHUB_OUTPUT
        else
          echo "deps-bin=$HOME/.local/bin" >> $GITHUB_OUTPUT
          echo "deps-cache=$HOME/.deps" >> $GITHUB_OUTPUT
          echo "tools-dir=$HOME/.local/opt" >> $GITHUB_OUTPUT
        fi

        echo "BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV
        echo "CACHE_DIR=$HOME/.deps" >> $GITHUB_ENV
        echo "APP_DIR=$HOME/.local/opt" >> $GITHUB_ENV
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Restore deps binary cache
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: ${{ steps.cache-paths.outputs.deps-bin }}/deps
        key: >-
          deps-binary-${{ runner.os }}-${{ runner.arch }}-
          ${{ inputs.deps-version }}

    - name: Restore tools cache
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.cache-paths.outputs.tools-dir }}
          ${{ steps.cache-paths.outputs.deps-cache }}
        key: >-
          deps-tools-${{ runner.os }}-${{ runner.arch }}-
          ${{ hashFiles(inputs.tools) }}

    - name: Install deps binary
      shell: bash
      run: |
        DEPS_BIN="${{ steps.cache-paths.outputs.deps-bin }}"
        mkdir -p "$DEPS_BIN"

        # Skip if cached
        if [ -f "$DEPS_BIN/deps" ]; then
          echo "deps binary found in cache"
          chmod +x "$DEPS_BIN/deps"
        else
          echo "Installing deps binary..."

          # Determine platform and architecture
          OS="${RUNNER_OS,,}"
          if [ "$OS" == "macos" ]; then
            OS="darwin"
          fi

          ARCH="${RUNNER_ARCH}"
          if [ "$ARCH" == "X64" ]; then
            ARCH="amd64"
          elif [ "$ARCH" == "ARM64" ]; then
            ARCH="arm64"
          fi

          VERSION="${{ inputs.version }}"

          # Determine archive extension based on OS
          if [ "$OS" == "windows" ]; then
            ARCHIVE_EXT=".zip"
          else
            ARCHIVE_EXT=".tar.gz"
          fi

          # Build download URL with archive extension
          BASE_URL="https://github.com/flanksource/deps/releases"
          if [ "$VERSION" == "latest" ]; then
            DOWNLOAD_URL="$BASE_URL/latest/download/deps-${OS}-${ARCH}${ARCHIVE_EXT}"
          else
            DOWNLOAD_URL="$BASE_URL/download/${VERSION}/deps-${OS}-${ARCH}${ARCHIVE_EXT}"
          fi

          # Download archive
          ARCHIVE_FILE="$DEPS_BIN/deps-archive${ARCHIVE_EXT}"
          echo "Downloading from: $DOWNLOAD_URL"
          curl -L -o "$ARCHIVE_FILE" "$DOWNLOAD_URL"

          # Extract binary from archive
          if [ "$OS" == "windows" ]; then
            unzip -q "$ARCHIVE_FILE" -d "$DEPS_BIN"
          else
            tar -xzf "$ARCHIVE_FILE" -C "$DEPS_BIN"
          fi

          # Clean up archive
          rm -f "$ARCHIVE_FILE"

          # Make executable
          chmod +x "$DEPS_BIN/deps"

          # Verify installation
          if [ ! -f "$DEPS_BIN/deps" ]; then
            echo "Failed to extract deps binary"
            exit 1
          fi
        fi

        # Add to PATH
        echo "$DEPS_BIN" >> $GITHUB_PATH

        # Verify deps works
        "$DEPS_BIN/deps" --help

    - name: Parse and install tools
      id: install
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        TOOLS_INPUT="${{ inputs.tools }}"

        # Parse tools (handle both comma-separated and multiline)
        TOOLS=$(echo "$TOOLS_INPUT" | tr ',' ' ' | tr -d '\r' | tr '\n' ' ' | \
          sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$')

        echo "Installing tools: $TOOLS"

        # Install all tools in a single call
        if [ -n "$TOOLS" ]; then
          deps install --no-progress $TOOLS

          if [ $? -ne 0 ]; then
            echo "Failed to install tools"
            exit 1
          fi
        fi
