name: Release

on:
  push:
    branches: [main, master]

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  id-token: write

env:
  GO_VERSION: "1.25"

jobs:
  version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.svu.outputs.version }}
      tag: ${{ steps.svu.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install svu
        run: |
          curl -sL https://github.com/caarlos0/svu/releases/download/v2.2.0/svu_2.2.0_linux_amd64.tar.gz | tar xz
          sudo mv svu /usr/local/bin/

      - name: Get next version
        id: svu
        run: |
          git fetch --tags
          NEXT_VERSION=$(svu patch --tag.pattern "v*)
          echo "version=${NEXT_VERSION#v}" >> $GITHUB_OUTPUT
          echo "tag=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "Next version: $NEXT_VERSION"

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.svu.outputs.tag }}
          git push origin ${{ steps.svu.outputs.tag }}
  build:
    name: Build
    needs: version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
          VERSION: ${{ needs.version.outputs.version }}
        run: |
          BINARY_NAME="deps"
          if [ "$GOOS" = "windows" ]; then
            BINARY_NAME="deps.exe"
          fi

          go build -ldflags="-s -w -X main.version=$VERSION -X main.commit=${{ github.sha }} -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            -o "$BINARY_NAME" ./cmd/deps/main.go


          sha256sum "$BINARY_NAME" > "$BINARY_NAME".sha256

      - name: Create archive
        run: |
          VERSION="${{ needs.version.outputs.version }}"
          GOOS="${{ matrix.goos }}"
          GOARCH="${{ matrix.goarch }}"


          ARCHIVE_NAME="deps-${GOOS}-${ARCH}"

          if [ "$GOOS" = "windows" ]; then
            zip "${ARCHIVE_NAME}.zip" deps.exe
            sha256sum  "${ARCHIVE_NAME}.zip" >  "${ARCHIVE_NAME}.sha256"
          else
            tar czf "${ARCHIVE_NAME}.tar.gz" deps
            sha256sum  "${ARCHIVE_NAME}.tar.gz" >  "${ARCHIVE_NAME}.tar.gz.sha256"
          fi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: deps*
          tag: ${{ github.ref }}

  release:
    name: Create Release
    needs: [version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find artifacts -type f -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" | while read file; do
            cp "$file" release/
          done
          ls -la release/

      - name: Generate checksums file
        run: |
          cd release
          sha256sum *.tar.gz *.zip > checksums.txt
          cat checksums.txt

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.version.outputs.tag }}
        run: |
          gh release create "$TAG" \
            --title "Release $TAG" \
            --generate-notes \
            release/*
