name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Unit tests run on ubuntu-latest
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: task test:unit

  # Linux installation tests - full installation and execution
  test-full:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-latest
            os: linux
            arch: amd64
          - runner: ubuntu-24.04-arm
            os: linux
            arch: arm64

          - runner: ubuntu-latest
            os: darwin
            arch: amd64
          - runner: ubuntu-latest
            os: darwin
            arch: arm64
          - runner: ubuntu-latest
            os: windows
            arch: amd64
    runs-on: ${{ matrix.platform.runner }}
    name: Install Tests - ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: task test
        env:
          TEST_OS: ${{ matrix.platform.os }}
          TEST_ARCH: ${{ matrix.platform.arch }}
