name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Unit tests run on ubuntu-latest
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: task test:unit

  # Linux installation tests - full installation and execution
  test-full:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-latest
            os: linux
            arch: amd64
          - runner: ubuntu-24.04-arm64
            os: linux
            arch: arm64
    runs-on: ${{ matrix.platform.runner }}
    name: Install Tests - ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: task test:e2e

  # Checksum validation tests for Darwin and Windows
  test-install-only:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
    name: Checksum Tests - ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: task test
        env:
          TEST_OS: ${{ matrix.platform.os }}
          TEST_ARCH: ${{ matrix.platform.arch }}
          SKIP_VERSION_CHECK: "true"
