name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Unit tests run on ubuntu-latest
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: ginkgo -v --skip-package=e2e ./...

  # Linux installation tests - full installation and execution
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-latest
            os: linux
            arch: amd64
          - runner: ubuntu-24.04-arm64
            os: linux
            arch: arm64
    runs-on: ${{ matrix.platform.runner }}
    name: Install Tests - ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Download dependencies
        run: go mod download

      - name: Run installation tests
        run: ginkgo -v ./e2e -focus="Installation tests.*${{ matrix.platform.os }}-${{ matrix.platform.arch }}"

  # Checksum validation tests for Darwin and Windows
  test-checksums:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
    name: Checksum Tests - ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Download dependencies
        run: go mod download

      - name: Run checksum validation tests
        run: ginkgo -v ./e2e -focus="Checksum validation tests.*${{ matrix.platform.os }}-${{ matrix.platform.arch }}"
